# Generated by Django 3.2 on 2021-04-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='PhotoFileName',
        ),
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(default='', upload_to='Employee/images'),
        ),
    ]
