# Generated by Django 3.2 on 2021-04-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Advisor',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Book',
        ),
    ]
