# Generated by Django 3.2 on 2021-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20210422_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='DepartmentId',
            new_name='AdvisorId',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='DepartmentName',
            new_name='AdvisorName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Department',
            new_name='Departmet',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='EmployeeId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='EmployeeName',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
